config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  draw :accounts
  draw :api
  draw :billing
  draw :hotwire_native
  draw :users
  draw :dev if Rails.env.local?

  authenticated :user, lambda { |u| u.admin? } do
    draw :madmin
  end

  resources :announcements, only: [:index, :show]

  namespace :action_text do
    resources :embeds, only: [:create], constraints: {id: /[^\/]+/} do
      collection do
        get :patterns
      end
    end
  end

  scope controller: :static do
    get :about
    get :terms
    get :privacy
    get :pricing
    get :reset_app
  end

  match "/404", via: :all, to: "errors#not_found"
  match "/500", via: :all, to: "errors#internal_server_error"

  authenticated :user do
    root to: "dashboard#show", as: :user_root
    # Alternate route to use if logged in users should still see public root
    # get "/dashboard", to: "dashboard#show", as: :user_root
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Public marketing homepage
  root to: "static#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w[new fix improvement update]

  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where.not(published_at: nil) }

  has_rich_text :description

  validates :kind, :title, :description, presence: true

  attribute :published_at, default: -> { Time.current }

  def self.unread?(user)
    most_recent_announcement = published.maximum(:published_at)
    most_recent_announcement && (user.nil? || user.announcements_read_at&.before?(most_recent_announcement))
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @pagy, @announcements = pagy(Announcement.published.order(published_at: :desc))
  end

  def show
    @announcement = Announcement.published.find(params[:id])
  end

  private

  def mark_as_read
    current_user.update(announcements_read_at: Time.current)
  end
end

app/controllers/madmin/announcements_controller.rb
module Madmin
  class AnnouncementsController < Madmin::ResourceController
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  # Use the explicit names so they don't get purged
  ANNOUNCEMENT_COLORS = {
    "new" => "announcement-new",
    "update" => "announcement-update",
    "improvement" => "announcement-improvement",
    "fix" => "announcement-fix"
  }

  def announcement_color(announcement)
    ANNOUNCEMENT_COLORS.fetch(announcement.kind, "announcement-update")
  end
end

app/views/announcements/_announcement.html.erb
<div class="p-4 lg:p-10" id="<%= dom_id(announcement) %>">
  <%= link_to announcement_path(announcement), class: "text-gray-400 text-sm font-medium capitalize" do %>
    <%= local_relative_time announcement.published_at, 'weekday-or-date' %>
  <% end %>

  <h2 class="font-semibold text-gray-900 text-lg mb-2 dark:text-gray-100"><%= announcement.title %></h2>
  <%= badge announcement.kind.humanize.titleize, class: "mb-2", color: announcement_color(announcement) %>

  <div class="text-gray-700 text-sm dark:text-gray-300">
    <%= announcement.description %>
  </div>
</div>

app/views/announcements/index.html.erb
<div class="container mx-auto max-w-4xl">
  <h1 class="h2 mt-6 text-center"><%= t(".title") %></h1>
  <p class="mt-2 text-center text-xl text-gray-700 dark:text-gray-300/75"><%= t(".description", name: Jumpstart.config.application_name) %></p>

  <div class="mt-6 flex flex-col rounded-lg divide-y divide-gray-200 bg-white border border-gray-200 dark:bg-gray-900 dark:border-gray-700 dark:divide-gray-700">
    <%= render @announcements %>

    <% if @announcements.empty? %>
      <div class="p-4 lg:p-10"><%= t(".empty_placeholder") %></div>
    <% end %>
  </div>

  <% if @pagy.pages > 1 %>
    <div class="text-center mt-8">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/announcements/show.html.erb
<div class="container mx-auto max-w-4xl">
  <h1 class="h2 mt-6 text-center"><%= t(".title") %></h1>
  <p class="mt-2 text-center text-xl text-gray-700 dark:text-gray-300/75"><%= t(".description", name: Jumpstart.config.application_name) %></p>

  <%= link_to announcements_path, class: "text-sm font-medium" do %>
    &larr;
    <%= t(".back") %>
  <% end %>

  <div class="mt-6 flex flex-col rounded-lg bg-white border border-gray-200 dark:bg-gray-900 dark:border-gray-700">
    <%= render @announcement %>
  </div>
</div>